#!/usr/bin/env bash
# Bash script to display time for 12 hours and 59 minutes using a while loop

hours=0

while [ $hours -le 12 ]
do
minutes=1
while [ $minutes -le 59 ]
do
echo "$hours:$minutes"
((minutes++))
    done

    ((hours++))
done

